//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TypeWell
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TypeWell20181021111715_dbEntities : DbContext
    {
        public TypeWell20181021111715_dbEntities()
            : base("name=TypeWell20181021111715_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<database_firewall_rules> database_firewall_rules { get; set; }
        public virtual DbSet<LANGUAGE> LANGUAGEs { get; set; }
        public virtual DbSet<LANGUAGE1> LANGUAGEs1 { get; set; }
        public virtual DbSet<LENGTH> LENGTHs { get; set; }
        public virtual DbSet<LENGTH1> LENGTHs1 { get; set; }
        public virtual DbSet<TEXT> TEXTs { get; set; }
        public virtual DbSet<TEXT1> TEXTs1 { get; set; }
        public virtual DbSet<database_firewall_rules1> database_firewall_rules1 { get; set; }
    }
}
