//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TypeWell
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEXT
    {
        public int Id { get; set; }
        public string TextForTest { get; set; }
        public Nullable<int> NumOfSymbols { get; set; }
        public int Language { get; set; }
        public int Length { get; set; }
    
        public virtual LANGUAGE LANGUAGE1 { get; set; }
        public virtual LENGTH LENGTH1 { get; set; }
    }
}
